### ISSUE TITLE
Entity 复用逻辑问题

### ISSUE THREAD

**Issue by FingerCaster** [HeNuoScott/GameFrameworkTemplate#1]
UGF的Entity 复用EntityLogic 时 有一个判断 
![image](https://user-images.githubusercontent.com/31885840/142126888-5b4a5e6c-4550-48a5-ad1a-2369aa5547d6.png)
这里的判断逻辑type 相等 需要自己做处理  因为所有的热更entitylogic都是HotEntity 导致如果一个实体 使用不同逻辑的话 无法移除当前逻辑脚本。

**Comment by HeNuoScott** [comment]
1. 一般情况一下 一种实体 只有一种逻辑 ,如果使用不同逻辑 你可以设置多个实体
2. 你也可以更改一下执行初始顺序到OnShow中 每次初始化都新加逻辑上去

**Comment by FingerCaster** [comment]
是的 我知道可以这样绕过去 但是这样的话 就和UGF 原有逻辑 不同了
